### ISSUE TITLE
提案内容整理

### ISSUE THREAD

**Issue by tkdkng** [TakahashiGrpHCS/VideoRental#1]
4/27　次回相談　←4/28停滞

**Comment by tkdkng** [comment]
[個人情報保護法.txt](https://github.com/TakahashiGrpHCS/VideoRental/files/960627/default.txt)
[第1回提案事項.txt](https://github.com/TakahashiGrpHCS/VideoRental/files/960626/1.txt)
[第１提案事項exl.xlsx](https://github.com/TakahashiGrpHCS/VideoRental/files/960628/exl.xlsx)

**Comment by DSTLC-VSIN** [comment]
細分化します
