### ISSUE TITLE
会員を確認する作業　業務フロー図作成

### ISSUE THREAD

**Issue by tori114** [TakahashiGrpHCS/VideoRental#5]
![default](https://cloud.githubusercontent.com/assets/28084917/25509794/6d68a42a-2bf6-11e7-9a7c-5c86a40305cc.png)

**Comment by yuugo0724** [comment]
レビューしました
再登録の処理とブラック会員の判定、会員特定不可がどういったものか書かれていないので文字でおこしていこうと思います。
会員特定処理オッケーです！

**Comment by tori114** [comment]
![default](https://cloud.githubusercontent.com/assets/28084917/25518247/fc6a7f90-2c2d-11e7-89bf-b2d3c6681227.png)

**Comment by tori114** [comment]
![default](https://cloud.githubusercontent.com/assets/28084917/25520163/e8331ef8-2c35-11e7-9519-32c5806a886d.png)

**Comment by yuugo0724** [comment]
オッケーです
