### ISSUE TITLE
入会手続き　業務フロー図作成

### ISSUE THREAD

**Issue by nekoten09** [TakahashiGrpHCS/VideoRental#6]
![default](https://cloud.githubusercontent.com/assets/28085255/25519522/1f356a58-2c33-11e7-8bf4-ed094765c1ec.png)

**Comment by DSTLC-VSIN** [comment]
割引券の受け渡しと入会金の支払いが逆では？

**Comment by yuugo0724** [comment]
レビューしました
身分証の種類がどれくらいあるかわからないので考えてみます。
登録日という言い方ではわかりにくいので今日の日付を登録していることをわかるような名前に変えてください！
