### ISSUE TITLE
現行業務フロー図作成

### ISSUE THREAD

**Issue by tori114** [TakahashiGrpHCS/VideoRental#7]
![default](https://cloud.githubusercontent.com/assets/28084917/25510547/df108520-2bfb-11e7-93fd-512ee3ee1c1d.png)

**Comment by yuugo0724** [comment]
おーありがとう！

**Comment by yuugo0724** [comment]
レビューしました
途中までということで残りのフローチャートを作ってほしいです。
会員情報の確認処理を文字でおこしたいとおもいます！

**Comment by tori114** [comment]
![default](https://cloud.githubusercontent.com/assets/28084917/25519846/6c6f7c90-2c34-11e7-9344-5d5ccf90ee4a.png)

**Comment by yuugo0724** [comment]
オッケーです
ありがとう！
